$w1 = /home/glow/Pictures/wallpapers/spiderman/miles2.jpg
$w2 = /home/glow/Pictures/wallpapers/spiderman/miles3.jpg

preload = $w1
preload = $w2
splash = false

wallpaper {
  monitor = eDP-1
  path = $w1
}

wallpaper {
  monitor = DP-4
  path = $w2
}
