$we = /home/glow/Pictures/wallpapers/spiderman/miles3.jpg
$w1 = /home/glow/Pictures/wallpapers/spiderman/1.png
$w2 = /home/glow/Pictures/wallpapers/spiderman/2.png

preload = $we
preload = $w1
preload = $w2

splash = false

wallpaper {
  monitor = eDP-1
  path = $we
}

wallpaper {
  monitor = DP-2
  path = $w1
}

wallpaper {
  monitor = DP-1
  path = $w2
}
