# monitors
monitorv2 { # mid
  output = DP-4
  mode = 1920x1080@144.00Hz
  position = 0x0
  scale = 1
}
monitorv2 { # right
  output = DP-3
  mode = 1920x1080@100.00Hz
  sdrsaturation = 1.5
  position = -1920x0
  scale = 1
}
monitorv2 { # internal (left)
  output = eDP-1
  mode = 2256x1504@60.00Hz
  position = 1920x0
  scale = 1.175
}

xwayland {
  force_zero_scaling = true
}

# workspaces
workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1

# workspace = 5, monitor:DP-3, default:true
# workspace = 6, monitor:DP-3
# workspace = 7, monitor:DP-3
# workspace = 8, monitor:DP-3
#
# workspace = 9,  monitor:eDP-1, default:true
# workspace = 10, monitor:eDP-1


workspace = 11, on-created-empty:kitty
workspace = 12, on-created-empty:sone # music
workspace = 13, on-created-empty:vesktop # discord
workspace = 14, on-created-empty:gtk-launch WebApp-youtube1696.desktop
workspace = 15, on-created-empty:gtk-launch WebApp-piracywebsite5155.desktop
workspace = 16, on-created-empty:zen-browser
workspace = 17, on-created-empty:kitty -d ~/Documents/ yazi
workspace = 18, on-created-empty:obsidian
workspace = 19, on-created-empty:vscodium
workspace = 20, on-created-empty:zeditor
workspace = 21, on-created-empty:android-studio
workspace = 22, on-created-empty:gimp
workspace = 23, on-created-empty:kitty -d ~/.dots nvim
