listener {
  timeout     = 90
  on-timeout  = brightnessctl -s & brightnessctl s 1%
  on-resume   = brightnessctl -r
}

listener {
  timeout     = 120
  on-timeout  = brightnessctl s 0
}

listener {
  timeout     = 300
  on-timeout  = noctalia msg session lock
  on-resume   = notify-send hi o/
}

listener {
  timeout     = 900
  on-timeout  = systemctl suspend
}
