[mgr]
prepend_keymap= [
  { on = ["`"], desc = "Command palette (fzf)", run = "plugin command-palette" },
  # backup
  # { on = "<S-y>", run = "plugin ucp copy", desc = "Copy" },
  # { on = "<S-y>", run = "plugin ucp copy notify", desc = "Copy" }
  { on = "y", run = "plugin ucp copy", desc = "Copy" },
  { on = "y", run = "plugin ucp copy notify", desc = "Copy" }
]
