[opener]
nvim = [
  { run = '''nvim "$@"''', desc = "Neovim" }
]
firefox = [
  { run = '''firefox "$@"''', desc = "Firefox" }
]
fiji = [
  { run = '''fiji "$@"''', desc = "Fiji" }
]
image = [
  { run = '''feh "$@"''', desc = 'feh' }
]
gwen = [
  { run = '''gwenview "$@"''', desc = 'gwen' }
]
zath = [
  { run = '''zathura "$@"''', desc = 'Zathura' }
]
zath_alt = [
  { run = '''azath "$@"''', desc = 'Zathura (no theming)' }
]
mpv = [
  { run = '''mpv "$@"''', desc = 'mpv'}
]
play = [
  { run = '''play "$@"''', desc = 'play'}
]
audacity = [
  { run = '''audacity "$@"''', desc = 'audacity'}
]

[open]
prepend_rules = [
  { url = "*.tif", use = "fiji" },
  { url = "*.html", use = ["firefox", "edit"] },
  { url = '*.czi', use = 'fiji' },
  { url = '*.png', use = ['image', 'gwen'] },
  { url = '*.jpg', use = ['image', 'gwen'] },
  { url = '*.pdf', use = ['zath', 'zath_alt', 'firefox'] },
  { url = '*.webm', use = 'mpv' },
  { url = '*.mp4', use = 'mpv' },
  { url = '*.mp3', use = ['play', 'audacity'] },
]
